version: '3.4'
volumes:
  es-data-basic:

services:
  collector:
    build: collector
    environment:
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET_KEY=${TWITTER_API_SECRET_KEY}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    restart: always
    volumes:
      - ./conf/:/conf/
    depends_on:
      - elasticsearch

  elasticsearch:
    build: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data-basic:/usr/share/elasticsearch/data

  kibana:
    build: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

